"""Video rendering functionality for tts-pipeline."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Default metadata for video uploads
DEFAULT_METADATA = {
    "artist": "VI AI for Good Foundation",
    "album_artist": "VI AI for Good Foundation",
    "copyright": "© 2025-2026 VI AI for Good Foundation · 501(c)(3)",
    "comment": "viaiforgood.org | Generated by tts-pipeline",
    "url": "https://viaiforgood.org",
}

AUDIO_EXTENSIONS = {".mp3", ".m4a", ".wav", ".aac", ".flac", ".ogg", ".opus"}


def check_ffmpeg() -> bool:
    """Check if FFmpeg is installed and accessible in the system PATH."""
    try:
        result = subprocess.run(["ffmpeg", "-version"], capture_output=True, text=True)
        return result.returncode == 0
    except FileNotFoundError:
        return False


def get_default_background() -> Path | None:
    """Resolve the default background image, preferring .jpg then .png."""
    # Try relative to the package location
    package_dir = Path(__file__).resolve().parent
    repo_root = package_dir.parents[2]

    search_dirs = [
        repo_root / "assets" / "background",
        Path.cwd() / "assets" / "background",
    ]

    for bg_dir in search_dirs:
        if bg_dir.exists():
            for ext in (".jpg", ".jpeg", ".png"):
                candidate = bg_dir / f"background{ext}"
                if candidate.exists():
                    return candidate
    return None


def render_audio_to_video(
    audio_path: str | Path,
    image_path: str | Path | None = None,
    output_path: str | Path | None = None,
    resolution: str = "1920x1080",
    audio_bitrate: str = "192k",
    no_meta: bool = False,
) -> Path:
    """Create an MP4 video from an audio file with a static background image using FFmpeg.

    Args:
        audio_path: Path to the input audio file.
        image_path: Optional path to the background image. If None, resolves default background.
        output_path: Optional path for the output video. Defaults to replacing extension with .mp4.
        resolution: Output video resolution (e.g., '1920x1080').
        audio_bitrate: Audio bitrate (e.g., '192k').
        no_meta: If True, skips embedding metadata.

    Returns:
        Path: The path to the created MP4 file.

    Raises:
        RuntimeError: If FFmpeg is not found or fails to run.
        FileNotFoundError: If input files cannot be resolved.
        ValueError: If parameters are invalid.
    """
    if not check_ffmpeg():
        raise RuntimeError(
            "FFmpeg not found. Please install FFmpeg (e.g., 'brew install ffmpeg' on macOS)."
        )

    # Validate audio path
    audio_p = Path(audio_path).resolve()
    if not audio_p.exists() or not audio_p.is_file():
        raise FileNotFoundError(f"Input audio file not found: {audio_path}")

    # Resolve background image path
    if image_path:
        image_p = Path(image_path).resolve()
        if not image_p.exists() or not image_p.is_file():
            raise FileNotFoundError(f"Background image file not found: {image_path}")
    else:
        bg_candidate = get_default_background()
        if not bg_candidate:
            raise FileNotFoundError(
                "No default background image found. "
                "Please specify one via --image or place background.jpg/png in assets/background/."
            )
        image_p = bg_candidate

    # Resolve output path
    if output_path:
        output_p = Path(output_path).resolve()
    else:
        output_p = audio_p.with_suffix(".mp4")

    # Validate resolution
    try:
        width, height = resolution.split("x")
        int(width)
        int(height)
    except ValueError:
        raise ValueError(f"Invalid resolution format: '{resolution}'. Expected format: WIDTHxHEIGHT")

    # Build ffmpeg command
    scale_filter = (
        f"scale={width}:{height}:force_original_aspect_ratio=decrease,"
        f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2"
    )

    cmd = [
        "ffmpeg",
        "-loop", "1",
        "-i", str(image_p),
        "-i", str(audio_p),
        "-c:v", "libx264",
        "-tune", "stillimage",
        "-vf", scale_filter,
        "-c:a", "aac",
        "-b:a", audio_bitrate,
        "-pix_fmt", "yuv420p",
        "-shortest",
    ]

    # Setup metadata
    metadata = {} if no_meta else DEFAULT_METADATA.copy()
    metadata["title"] = audio_p.stem.replace("_", " ").replace("-", " ")

    for key, val in metadata.items():
        cmd.extend(["-metadata", f"{key}={val}"])

    cmd.extend(["-y", str(output_p)])

    print(f"🎬 Creating MP4: {output_p.name}")
    print(f"   Audio: {audio_p}")
    print(f"   Image: {image_p}")

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"FFmpeg error during render:\n{result.stderr}")

    print(f"✅ Created video: {output_p}")
    return output_p


def batch_render_audio_to_video(
    folder_path: str | Path,
    image_path: str | Path | None = None,
    output_dir: str | Path | None = None,
    resolution: str = "1920x1080",
    audio_bitrate: str = "192k",
    no_meta: bool = False,
) -> tuple[int, int]:
    """Convert all audio files in a directory to MP4 videos.

    Returns:
        A tuple of (success_count, failure_count).
    """
    folder_p = Path(folder_path).resolve()
    if not folder_p.exists() or not folder_p.is_dir():
        raise FileNotFoundError(f"Folder not found: {folder_path}")

    audio_files = sorted(
        p for p in folder_p.iterdir()
        if p.is_file() and p.suffix.lower() in AUDIO_EXTENSIONS
    )

    if not audio_files:
        print(f"No audio files found in: {folder_p}")
        return 0, 0

    out_dir_p = Path(output_dir).resolve() if output_dir else folder_p
    out_dir_p.mkdir(parents=True, exist_ok=True)

    print(f"\n📂 Batch converting {len(audio_files)} file(s) from: {folder_p}")
    print(f"   Output dir: {out_dir_p}\n")

    success_cnt = 0
    failure_cnt = 0

    for i, audio_p in enumerate(audio_files, 1):
        print(f"── [{i}/{len(audio_files)}] {audio_p.name}")
        out_p = out_dir_p / audio_p.with_suffix(".mp4").name
        try:
            render_audio_to_video(
                audio_path=audio_p,
                image_path=image_path,
                output_path=out_p,
                resolution=resolution,
                audio_bitrate=audio_bitrate,
                no_meta=no_meta,
            )
            success_cnt += 1
        except Exception as e:
            print(f"❌ Failed to convert {audio_p.name}: {e}", file=sys.stderr)
            failure_cnt += 1
        print()

    print(f"\n{'='*50}")
    print(f"📊 Batch complete: {success_cnt} succeeded, {failure_cnt} failed out of {len(audio_files)}")
    return success_cnt, failure_cnt
